### ISSUE TITLE
0.6.8-rc2 - Unable to repack config file

### ISSUE THREAD

**Issue by hunt3vil** [Velocidex/velociraptor#2540]
I am unable to repack a config file into the Velo binary with 0.6.8-RC2. This was working with 0.6.8-RC1 I tried both Linux and Windows binaries:

```
/bin/velociraptor-v0.6.8-rc2-linux-amd64-musl config repack ~/config.yaml /bin/velociraptor-v0.6.8-rc2-windows-amd64.exe 
velociraptor-v0.6.8-rc2-linux-amd64-musl: error: config repack: Unable to load config file: Unable to load config from any source.
```

```
.\bin\velociraptor-v0.6.8-rc2-windows-amd64.exe config repack ~\config.yaml .\bin\velociraptor-v0.6.8-rc2-windows-amd64.exe
velociraptor-v0.6.8-rc2-windows-amd64.exe: error: config repack: Unable to load config file: Unable to load config from any source.
```

**Comment by scudette** [comment]
sorry there was a last minute issue with rc2 so I pushed rc3 quickly after. You must have been quick to test :-)

```
$ ./output/velociraptor-v0.6.8-rc3-linux-amd64-musl config repack ~/client.config.yaml /tmp/test.bin
[
 {
  "RepackInfo": {
   "Path": "/tmp/test.bin",
   "Size": 51160296,
   "sha256": "78aeb63543c5f741e677475ad9fd8589fa69961ee3524ba988b5294324d7db90",
   "md5": "c2e5302115a7f0e750fae9643223bac0",
   "Components": [
    "test.bin"
   ]
  }
 }
]

$ chmod +x /tmp/test.bin
$ /tmp/test.bin config show | head
version:
  name: velociraptor
  version: 0.6.8-rc3
  commit: 7e9e42a
  build_time: "2023-03-14T02:04:10Z"
  install_time: 1677518989
  ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/4411426113
  compiler: go1.20.1
```

**Comment by hunt3vil** [comment]
Hmm this still doesn't work for me with rc3; same error. Let me know if there are any logs I can provide.

**Comment by scudette** [comment]
Make sure the client configuration is actually valid. Can you just run

Velociraptor --config client.config.yaml config show

It should just be able to load the config and print it if it validates

**Comment by hunt3vil** [comment]
Yep that works fine

**Comment by scudette** [comment]
Can you use the -v flag during the repack? Maybe it can tell us something about what's happening

**Comment by hunt3vil** [comment]
No change

```
.\bin\velociraptor-v0.6.8-rc3-windows-amd64.exe -v config repack .\build\config.yaml velo.exe
velociraptor-v0.6.8-rc3-windows-amd64.exe: error: config repack: Unable to load config file: Unable to load config from any source.
```

**Comment by scudette** [comment]
That's very strange... Is your config very large? Can you generate a new config with the wizard and pack that?

**Comment by hunt3vil** [comment]
Same error with freshly generated config

```
> .\bin\velociraptor-v0.6.8-rc3-windows-amd64.exe config generate > .\build\new_config.yaml
> .\bin\velociraptor-v0.6.8-rc3-windows-amd64.exe -v config repack .\build\new_config.yaml velo.exe
velociraptor-v0.6.8-rc3-windows-amd64.exe: error: config repack: Unable to load config file: Unable to load config from any source.
```

**Comment by scudette** [comment]
Hmm i checked with the windows version and I think I figured out the error. It needs to load the config first:

```
velociraptor-v0.6.8-rc3-windows-amd64.exe -v --config c:\datastore\client.config.yaml  config repack client.config.yaml out.exe
```

That should not be necessary though.

**Comment by hunt3vil** [comment]
Same thing with the Linux one for me

$ bin/velociraptor-v0.6.8-rc3-linux-amd64 config generate > ./build/config2.yaml
$ bin/velociraptor-v0.6.8-rc3-linux-amd64 config repack ./build/config2.yaml velo.bin
velociraptor-v0.6.8-rc3-linux-amd64: error: config repack: Unable to load config file: Unable to load config from any source.
wsl@BLU-BFHMKG3:/home/user$ bin/velociraptor-v0.6.8-rc3-linux-amd64 --config ./build/config2.yaml config repack ./build/config2.yaml velo.bin
[
 {
  "RepackInfo": {
   "Path": "/home/user/velo.bin",
   "Size": 51026848,
   "sha256": "67a955397c6a6fd080a17f0cb8e2e11551210ad31a8cd42517693f1cd7c28351",
   "md5": "6439fe29abbdb1e0fed1c62efc2c5c92",
   "Components": [
    "velo.bin"
   ]
  }
 }
]

**Comment by scudette** [comment]
ok thanks for this! just verified that it requires a config to be loaded first (which is should not). So that is why it is not even starting the repack. You can provide one with --config flag but I have a quick fix i will push now.

Thanks again!
