### ISSUE TITLE
server_port in SMTP secret is ignored

### ISSUE THREAD

**Issue by misje** [Velocidex/velociraptor#4340]
When I specify a port in an SMTP secret, the value is not used by `mail()`. Could this be caused by secrets not supporting integers at all? If I try to create a custom secret type, and adding an integer default value, I get "Secret Template: proto: (line 1:93): invalid value for string field value: 25".

**Comment by misje** [comment]
I believe that the same goes for booleans (anything but strings), like skip_verify.

**Comment by scudette** [comment]
Should be fixed by #4342

**Comment by misje** [comment]
This still does not work in the latest build. Neither port nor skip_verify work. Additionally, I have to set the "server" argument to `mail()` even if a secret is specified.
