### ISSUE TITLE
Download CSV not working in some places

### ISSUE THREAD

**Issue by predictiple** [Velocidex/velociraptor#954]
Version 0.5.6 (45a12d4b)

For client and server flow results the Results and Log tabs have a Download CSV button. Clicking it redirects to a URI with a query parameter "total_rows" that is not expected, resulting in the error:
> schema: invalid path "total_rows"

Removing the "total_rows" parameter from the URI allows the CSV download to proceeed. The issue does not occur when using the Download CSV button on the Flow's Notebook tab or in the Notebooks section.

**Comment by scudette** [comment]
Fixed in 0.5.7

**Comment by predictiple** [comment]
I'm still getting this on the Log tab for Collected Artifacts with v0.5.7

**Comment by scudette** [comment]
Should be fixed again in head :-)

**Comment by predictiple** [comment]
It is working now. Thanks.
